#!/bin/bash

set -e

export CI=true

# OS
if [ "$1" = "os" ]; then
  # Install native dependencies
  dnf install -y @c-development @development-tools go curl make file cpio unzip rsync bc openssh-clients which wget perl awk

  # Configure Git
  git config --global --add safe.directory '*'

  cd os
  # Generate dependencies for OS
  make depend/os OS_DEFCONFIG="$2"

  # Build OS
  FORCE_UNSAFE_CONFIGURE=1 make build/os
  cd ..

  # Package OS
  go run ./cmd/drafter-packager --package-path "os/out/$3" --devices '[
      {
        "name": "kernel",
        "path": "out/blueprint/vmlinux"
      },
      {
        "name": "disk",
        "path": "out/blueprint/rootfs.ext4"
      }
    ]'

  exit 0
fi
