// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: seeder_with_meta.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SeederWithMetaClient is the client API for SeederWithMeta service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeederWithMetaClient interface {
	ReadAt(ctx context.Context, in *ReadAtArgs, opts ...grpc.CallOption) (*ReadAtReply, error)
	Track(ctx context.Context, in *TrackArgs, opts ...grpc.CallOption) (*TrackReply, error)
	Sync(ctx context.Context, in *SyncArgs, opts ...grpc.CallOption) (*SyncReply, error)
	Close(ctx context.Context, in *CloseArgs, opts ...grpc.CallOption) (*CloseReply, error)
	Meta(ctx context.Context, in *MetaArgs, opts ...grpc.CallOption) (*MetaReply, error)
}

type seederWithMetaClient struct {
	cc grpc.ClientConnInterface
}

func NewSeederWithMetaClient(cc grpc.ClientConnInterface) SeederWithMetaClient {
	return &seederWithMetaClient{cc}
}

func (c *seederWithMetaClient) ReadAt(ctx context.Context, in *ReadAtArgs, opts ...grpc.CallOption) (*ReadAtReply, error) {
	out := new(ReadAtReply)
	err := c.cc.Invoke(ctx, "/io.loopholelabs.architekt.migration.v1.SeederWithMeta/ReadAt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seederWithMetaClient) Track(ctx context.Context, in *TrackArgs, opts ...grpc.CallOption) (*TrackReply, error) {
	out := new(TrackReply)
	err := c.cc.Invoke(ctx, "/io.loopholelabs.architekt.migration.v1.SeederWithMeta/Track", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seederWithMetaClient) Sync(ctx context.Context, in *SyncArgs, opts ...grpc.CallOption) (*SyncReply, error) {
	out := new(SyncReply)
	err := c.cc.Invoke(ctx, "/io.loopholelabs.architekt.migration.v1.SeederWithMeta/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seederWithMetaClient) Close(ctx context.Context, in *CloseArgs, opts ...grpc.CallOption) (*CloseReply, error) {
	out := new(CloseReply)
	err := c.cc.Invoke(ctx, "/io.loopholelabs.architekt.migration.v1.SeederWithMeta/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seederWithMetaClient) Meta(ctx context.Context, in *MetaArgs, opts ...grpc.CallOption) (*MetaReply, error) {
	out := new(MetaReply)
	err := c.cc.Invoke(ctx, "/io.loopholelabs.architekt.migration.v1.SeederWithMeta/Meta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeederWithMetaServer is the server API for SeederWithMeta service.
// All implementations must embed UnimplementedSeederWithMetaServer
// for forward compatibility
type SeederWithMetaServer interface {
	ReadAt(context.Context, *ReadAtArgs) (*ReadAtReply, error)
	Track(context.Context, *TrackArgs) (*TrackReply, error)
	Sync(context.Context, *SyncArgs) (*SyncReply, error)
	Close(context.Context, *CloseArgs) (*CloseReply, error)
	Meta(context.Context, *MetaArgs) (*MetaReply, error)
	mustEmbedUnimplementedSeederWithMetaServer()
}

// UnimplementedSeederWithMetaServer must be embedded to have forward compatible implementations.
type UnimplementedSeederWithMetaServer struct {
}

func (UnimplementedSeederWithMetaServer) ReadAt(context.Context, *ReadAtArgs) (*ReadAtReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAt not implemented")
}
func (UnimplementedSeederWithMetaServer) Track(context.Context, *TrackArgs) (*TrackReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Track not implemented")
}
func (UnimplementedSeederWithMetaServer) Sync(context.Context, *SyncArgs) (*SyncReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedSeederWithMetaServer) Close(context.Context, *CloseArgs) (*CloseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedSeederWithMetaServer) Meta(context.Context, *MetaArgs) (*MetaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Meta not implemented")
}
func (UnimplementedSeederWithMetaServer) mustEmbedUnimplementedSeederWithMetaServer() {}

// UnsafeSeederWithMetaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeederWithMetaServer will
// result in compilation errors.
type UnsafeSeederWithMetaServer interface {
	mustEmbedUnimplementedSeederWithMetaServer()
}

func RegisterSeederWithMetaServer(s grpc.ServiceRegistrar, srv SeederWithMetaServer) {
	s.RegisterService(&SeederWithMeta_ServiceDesc, srv)
}

func _SeederWithMeta_ReadAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAtArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeederWithMetaServer).ReadAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.loopholelabs.architekt.migration.v1.SeederWithMeta/ReadAt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeederWithMetaServer).ReadAt(ctx, req.(*ReadAtArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeederWithMeta_Track_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeederWithMetaServer).Track(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.loopholelabs.architekt.migration.v1.SeederWithMeta/Track",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeederWithMetaServer).Track(ctx, req.(*TrackArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeederWithMeta_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeederWithMetaServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.loopholelabs.architekt.migration.v1.SeederWithMeta/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeederWithMetaServer).Sync(ctx, req.(*SyncArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeederWithMeta_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeederWithMetaServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.loopholelabs.architekt.migration.v1.SeederWithMeta/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeederWithMetaServer).Close(ctx, req.(*CloseArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeederWithMeta_Meta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeederWithMetaServer).Meta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.loopholelabs.architekt.migration.v1.SeederWithMeta/Meta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeederWithMetaServer).Meta(ctx, req.(*MetaArgs))
	}
	return interceptor(ctx, in, info, handler)
}

// SeederWithMeta_ServiceDesc is the grpc.ServiceDesc for SeederWithMeta service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeederWithMeta_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.loopholelabs.architekt.migration.v1.SeederWithMeta",
	HandlerType: (*SeederWithMetaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadAt",
			Handler:    _SeederWithMeta_ReadAt_Handler,
		},
		{
			MethodName: "Track",
			Handler:    _SeederWithMeta_Track_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _SeederWithMeta_Sync_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _SeederWithMeta_Close_Handler,
		},
		{
			MethodName: "Meta",
			Handler:    _SeederWithMeta_Meta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seeder_with_meta.proto",
}
