// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: seeder_with_size.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SeederWithSizeClient is the client API for SeederWithSize service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeederWithSizeClient interface {
	ReadAt(ctx context.Context, in *ReadAtArgs, opts ...grpc.CallOption) (*ReadAtReply, error)
	Track(ctx context.Context, in *TrackArgs, opts ...grpc.CallOption) (*TrackReply, error)
	Sync(ctx context.Context, in *SyncArgs, opts ...grpc.CallOption) (*SyncReply, error)
	Close(ctx context.Context, in *CloseArgs, opts ...grpc.CallOption) (*CloseReply, error)
	Size(ctx context.Context, in *SizeArgs, opts ...grpc.CallOption) (*SizeReply, error)
}

type seederWithSizeClient struct {
	cc grpc.ClientConnInterface
}

func NewSeederWithSizeClient(cc grpc.ClientConnInterface) SeederWithSizeClient {
	return &seederWithSizeClient{cc}
}

func (c *seederWithSizeClient) ReadAt(ctx context.Context, in *ReadAtArgs, opts ...grpc.CallOption) (*ReadAtReply, error) {
	out := new(ReadAtReply)
	err := c.cc.Invoke(ctx, "/io.loopholelabs.architekt.migration.v1.SeederWithSize/ReadAt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seederWithSizeClient) Track(ctx context.Context, in *TrackArgs, opts ...grpc.CallOption) (*TrackReply, error) {
	out := new(TrackReply)
	err := c.cc.Invoke(ctx, "/io.loopholelabs.architekt.migration.v1.SeederWithSize/Track", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seederWithSizeClient) Sync(ctx context.Context, in *SyncArgs, opts ...grpc.CallOption) (*SyncReply, error) {
	out := new(SyncReply)
	err := c.cc.Invoke(ctx, "/io.loopholelabs.architekt.migration.v1.SeederWithSize/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seederWithSizeClient) Close(ctx context.Context, in *CloseArgs, opts ...grpc.CallOption) (*CloseReply, error) {
	out := new(CloseReply)
	err := c.cc.Invoke(ctx, "/io.loopholelabs.architekt.migration.v1.SeederWithSize/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seederWithSizeClient) Size(ctx context.Context, in *SizeArgs, opts ...grpc.CallOption) (*SizeReply, error) {
	out := new(SizeReply)
	err := c.cc.Invoke(ctx, "/io.loopholelabs.architekt.migration.v1.SeederWithSize/Size", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeederWithSizeServer is the server API for SeederWithSize service.
// All implementations must embed UnimplementedSeederWithSizeServer
// for forward compatibility
type SeederWithSizeServer interface {
	ReadAt(context.Context, *ReadAtArgs) (*ReadAtReply, error)
	Track(context.Context, *TrackArgs) (*TrackReply, error)
	Sync(context.Context, *SyncArgs) (*SyncReply, error)
	Close(context.Context, *CloseArgs) (*CloseReply, error)
	Size(context.Context, *SizeArgs) (*SizeReply, error)
	mustEmbedUnimplementedSeederWithSizeServer()
}

// UnimplementedSeederWithSizeServer must be embedded to have forward compatible implementations.
type UnimplementedSeederWithSizeServer struct {
}

func (UnimplementedSeederWithSizeServer) ReadAt(context.Context, *ReadAtArgs) (*ReadAtReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAt not implemented")
}
func (UnimplementedSeederWithSizeServer) Track(context.Context, *TrackArgs) (*TrackReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Track not implemented")
}
func (UnimplementedSeederWithSizeServer) Sync(context.Context, *SyncArgs) (*SyncReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedSeederWithSizeServer) Close(context.Context, *CloseArgs) (*CloseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedSeederWithSizeServer) Size(context.Context, *SizeArgs) (*SizeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Size not implemented")
}
func (UnimplementedSeederWithSizeServer) mustEmbedUnimplementedSeederWithSizeServer() {}

// UnsafeSeederWithSizeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeederWithSizeServer will
// result in compilation errors.
type UnsafeSeederWithSizeServer interface {
	mustEmbedUnimplementedSeederWithSizeServer()
}

func RegisterSeederWithSizeServer(s grpc.ServiceRegistrar, srv SeederWithSizeServer) {
	s.RegisterService(&SeederWithSize_ServiceDesc, srv)
}

func _SeederWithSize_ReadAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAtArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeederWithSizeServer).ReadAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.loopholelabs.architekt.migration.v1.SeederWithSize/ReadAt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeederWithSizeServer).ReadAt(ctx, req.(*ReadAtArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeederWithSize_Track_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeederWithSizeServer).Track(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.loopholelabs.architekt.migration.v1.SeederWithSize/Track",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeederWithSizeServer).Track(ctx, req.(*TrackArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeederWithSize_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeederWithSizeServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.loopholelabs.architekt.migration.v1.SeederWithSize/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeederWithSizeServer).Sync(ctx, req.(*SyncArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeederWithSize_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeederWithSizeServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.loopholelabs.architekt.migration.v1.SeederWithSize/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeederWithSizeServer).Close(ctx, req.(*CloseArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeederWithSize_Size_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SizeArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeederWithSizeServer).Size(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.loopholelabs.architekt.migration.v1.SeederWithSize/Size",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeederWithSizeServer).Size(ctx, req.(*SizeArgs))
	}
	return interceptor(ctx, in, info, handler)
}

// SeederWithSize_ServiceDesc is the grpc.ServiceDesc for SeederWithSize service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeederWithSize_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.loopholelabs.architekt.migration.v1.SeederWithSize",
	HandlerType: (*SeederWithSizeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadAt",
			Handler:    _SeederWithSize_ReadAt_Handler,
		},
		{
			MethodName: "Track",
			Handler:    _SeederWithSize_Track_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _SeederWithSize_Sync_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _SeederWithSize_Close_Handler,
		},
		{
			MethodName: "Size",
			Handler:    _SeederWithSize_Size_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seeder_with_size.proto",
}
