name: Build OS

on:
  push:
  pull_request:

jobs:
  build-oci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: deps
        run: sudo apt install umoci

      - name: Setup dest
        run: |
          mkdir /tmp/os

      - name: Build OS 
        run: |
          cd os
          make clean/os
          make depend/os OS_DEFCONFIG=drafteros-oci-firecracker-x86_64_defconfig
          FORCE_UNSAFE_CONFIGURE=1 make build/os
          cd ..
          go run ./cmd/drafter-packager --package-path "/tmp/os/drafteros-oci-x86_64.tar.zst" --devices '[{"name": "kernel","path": "os/out/blueprint/vmlinux"},{"name": "disk","path": "os/out/blueprint/rootfs.ext4"}]'

      - name: Build OS KVM
        run: |
          cd os
          make clean/os
          make depend/os OS_DEFCONFIG=drafteros-oci-firecracker-x86_64_kvm_defconfig
          FORCE_UNSAFE_CONFIGURE=1 make build/os
          cd ..
          go run ./cmd/drafter-packager --package-path "/tmp/os/drafteros-oci-x86_64_pvm.tar.zst" --devices '[{"name": "kernel","path": "os/out/blueprint/vmlinux"},{"name": "disk","path": "os/out/blueprint/rootfs.ext4"}]'

      - name: Show os files
        run: ls /tmp/os -l

      - name: Publish pre-release to GitHub releases
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.ref_name }}
          prerelease: true
          files: |
            /tmp/os/*

      - name: Publish release to GitHub releases
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          files: |
            /tmp/os/*
