name: Firecracker Tests

on:
  pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Setup kvm
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup firecracker
        run: |
          gunzip fc/firecracker.gz
          sudo mv fc/firecracker /usr/bin/
          chmod 777 /usr/bin/firecracker
          gunzip fc/jailer.gz
          sudo mv fc/jailer /usr/bin/
          chmod 777 /usr/bin/jailer

      - name: Grab some blueprints
        run: |
          mkdir out
          mkdir out/blueprint
          wget -q https://github.com/loopholelabs/drafter/releases/download/v0.6.3/oci-valkey-x86_64.tar.zst
          wget -q https://github.com/loopholelabs/drafter/releases/download/v0.6.3/drafteros-oci-x86_64.tar.zst
          tar --zstd -xf oci-valkey-x86_64.tar.zst
          tar --zstd -xf drafteros-oci-x86_64.tar.zst
          mv oci out/blueprint/oci.ext4
          mv kernel out/blueprint/vmlinux
          mv disk out/blueprint/rootfs.ext4

      - name: Test
        run: go test -exec sudo -v ./... --tags integration
