name: Lint

on:
  pull_request

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
         version: latest
         args: --timeout=5m
