name: Migration Tests

on:
  pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false    
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Setup kvm
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup firecracker
        run: |
          sudo mv fc/firecracker_jun10 /usr/bin/firecracker
          chmod 777 /usr/bin/firecracker
          sudo mv fc/jailer_jun10 /usr/bin/jailer
          chmod 777 /usr/bin/jailer

      - name: Grab some blueprints
        run: |
          mkdir out
          mkdir out/blueprint
          wget -q https://github.com/loopholelabs/drafter/releases/download/v0.6.3/oci-valkey-x86_64.tar.zst
          wget -q https://github.com/loopholelabs/drafter/releases/download/v0.6.3/drafteros-oci-x86_64.tar.zst
          tar --zstd -xf oci-valkey-x86_64.tar.zst
          tar --zstd -xf drafteros-oci-x86_64.tar.zst
          mv oci out/blueprint/oci.ext4
          mv kernel out/blueprint/vmlinux
          mv disk out/blueprint/rootfs.ext4
          rm *.zst
          df -h

      - name: Build agent
        run: |
          cd cmd/drafter-agent
          go build .
          cd ../..
          mkdir tmproot
          sudo mount out/blueprint/rootfs.ext4 tmproot
          sudo mv cmd/drafter-agent/drafter-agent tmproot/usr/bin/drafter-agent
          sudo umount out/blueprint/rootfs.ext4
          rmdir tmproot

      - name: Disable swap
        run: |
          sudo swapoff -a
          cat /proc/swaps

      - name: Test
        run: go test -exec sudo -v ./pkg/runtimes/firecracker/. --tags "integration migration" --timeout 120m --run ^TestMigration
