name: Publish Artifacts

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download output
        uses: actions/download-artifact@v4
        with:
          path: /tmp/out

      - name: Publish pre-release to GitHub releases
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.ref_name }}
          prerelease: true
          files: |
            /tmp/out/*/*

      - name: Publish release to GitHub releases
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          files: |
            /tmp/out/*/*
